=== Zhenyria/masterjava/src/main/resources/payload.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://javaops.ru"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://javaops.ru"
           elementFormDefault="qualified">

    <xs:complexType name="payloadType">
        <xs:all>
            <xs:element name="cities">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element ref="City"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="users">
                <xs:complexType>
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element ref="User"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="projects">
                <xs:complexType>
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element ref="Project"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deleted"/>
            <xs:enumeration value="superuser"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="userType">
        <xs:sequence>
            <xs:element type="xs:string" name="fullName"/>
            <xs:element type="xs:IDREFS" name="groups" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="flagType" name="flag" use="required"/>
        <xs:attribute type="xs:string" name="email" use="required"/>
        <xs:attribute type="xs:IDREF" name="city" use="required"/>
    </xs:complexType>

    <xs:complexType name="cityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="projectType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" minOccurs="0" maxOccurs="250" name="description"/>
            <xs:element name="groups">
                <xs:complexType>
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element ref="Group"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="groupType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="name"/>
                <xs:attribute type="groupTypeType" name="type" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="groupTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="registering"/>
            <xs:enumeration value="current"/>
            <xs:enumeration value="finished"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="Payload" type="payloadType"/>
    <xs:element name="City" type="cityType"/>
    <xs:element name="User" type="userType"/>
    <xs:element name="Project" type="projectType"/>
    <xs:element name="Group" type="groupType"/>
</xs:schema>

=== Zhenyria/masterjava/src/test/resources/payload.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload.xsd">
    <users>
        <User flag="active" email="gmail@gmail.com" city="kiv">
            <fullName>Full Name</fullName>
            <groups>topJava01 topJava02</groups>
        </User>
        <User flag="superuser" email="admin@javaops.ru" city="spb">
            <fullName>Admin</fullName>
            <groups>topJava01 topJava02 topJava03 masterJava01 masterJava02</groups>
        </User>
        <User flag="deleted" email="mail@yandex.ru" city="spb">
            <fullName>Deleted</fullName>
            <groups>topJava01 masterJava01 masterJava02</groups>
        </User>
        <User flag="active" email="zhenyria@mail.ru" city="mnsk">
            <fullName>Zhenya</fullName>
            <groups>topJava02 masterJava02</groups>
        </User>
        <User flag="active" email="dog@mail.ru" city="kiv">
            <fullName>Jhonny Petrov</fullName>
            <groups>masterJava02</groups>
        </User>
    </users>
    <cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
    </cities>
    <projects>
        <Project>
            <name>topJava</name>
            <description>TopJava project</description>
            <groups>
                <Group type="finished" name="topJava01"/>
                <Group type="current" name="topJava02"/>
                <Group type="registering" name="topJava03"/>
            </groups>
        </Project>
        <Project>
            <name>masterJava</name>
            <description>MasterJava project</description>
            <groups>
                <Group type="finished" name="masterJava01"/>
                <Group type="registering" name="masterJava02"/>
            </groups>
        </Project>
    </projects>
</Payload>
